filebeat.inputs:
  - type: filestream
    id: backend
    fields_under_root: true
    encoding: utf-8
    fields:
      event.dataset: backend
    paths:
      - /var/log/backend/*.log

setup.kibana:
  host: "kibana:5601"
output.logstash:
  hosts: ["logstash:5001"]
